### ISSUE TITLE
@sassoftware/va-report-components giving error while integrating with Angular 16 

### ISSUE THREAD

**Issue by ivineettiwari** [sassoftware/sas-viya-sdk-js#67]
polyfills.e366e81215917462.js:1 Unhandled Promise rejection: Cannot find module './NovaComponents-SegmentedButton-gui-icu_en_US.properties' ; Zone: <root> ; Task: Promise.then ; Value: Error: Cannot find module './NovaComponents-SegmentedButton-gui-icu_en_US.properties'
    at NovaComponents\-.*\-gui\-icu.*\.properties$ namespace object:11998:12
    at v.invoke (polyfills.e366e81215917462.js:1:6580)
    at L.run (polyfills.e366e81215917462.js:1:1961)
    at polyfills.e366e81215917462.js:1:16790
    at v.invokeTask (polyfills.e366e81215917462.js:1:7198)
    at L.runTask (polyfills.e366e81215917462.js:1:2578)
    at _ (polyfills.e366e81215917462.js:1:9215) Error: Cannot find module './NovaComponents-SegmentedButton-gui-icu_en_US.properties'
    at http://localhost:4200/assets/sdk-assets/dist/umd/33.va-report-components.js:1:3376924
    at v.invoke (http://localhost:4200/polyfills.e366e81215917462.js:1:6580)
    at L.run (http://localhost:4200/polyfills.e366e81215917462.js:1:1961)
    at http://localhost:4200/polyfills.e366e81215917462.js:1:16790
    at v.invokeTask (http://localhost:4200/polyfills.e366e81215917462.js:1:7198)
    at L.runTask (http://localhost:4200/polyfills.e366e81215917462.js:1:2578)
    at _ (http://localhost:4200/polyfills.e366e81215917462.js:1:9215)

**Comment by brmorr** [comment]
Production issues should be reported and triaged through [customer support tickets](https://support.sas.com/en/technical-support/submit-a-support-request.html).
